name: Generate the latest brew formula
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install wheel
        run: pip install setuptools wheel 
      - name: Fetch latest release and regenerate formula
        run: bash publish-brew-formula.sh
